version: '3.8'

services:
  app:
    build: .
    container_name: crud_contatos
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: contatos_db
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin

  db:
    image: mysql:8.0
    container_name: contatos_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: contatos_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data:
